apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment  # Changed to match existing deployment name
  namespace: api-namespace  # Specify the namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: interview-api
  template:
    metadata:
      labels:
        app: interview-api
    spec:
      containers:
      - name: interview-api
        image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/interview/generalfocus/interview-api:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: Laravel
        - name: APP_ENV
          value: local
        - name: APP_KEY
          value: base64:ckMN/xIWBv7Ry35yb3qwqA41z1TNOvppdAAAyoJBA3Y=
        - name: APP_DEBUG
          value: "true"
        - name: APP_TIMEZONE
          value: UTC
        - name: APP_URL
          value: http://localhost
      imagePullSecrets:
      - name: artifact-registry-key 
---
apiVersion: v1
kind: Service
metadata:
  name: api-service  # Changed to match deployment or existing service
  namespace: api-namespace  # Specify the namespace
spec:
  type: LoadBalancer
  selector:
    app: interview-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
