apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: interview-api
  template:
    metadata:
      labels:
        app: interview-api
    spec:
      containers:
      - name: interview-api
        image: gcr.io/whatthetime/generalfocus/interview-api:latest  # Replace 'my-gcp-project' with your actual project ID
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: Laravel
        - name: APP_ENV
          value: local
        - name: APP_KEY
          value: base64:ckMN/xIWBv7Ry35yb3qwqA41z1TNOvppdAAAyoJBA3Y=
        - name: APP_DEBUG
          value: "true"
        - name: APP_TIMEZONE
          value: UTC
        - name: APP_URL
          value: http://localhost
---
apiVersion: v1
kind: Service
metadata:
  name: interview-api-service
spec:
  type: LoadBalancer
  selector:
    app: interview-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80