name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
      GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
      DOCKER_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/generalfocus/interview-api:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use Google Container Registry
      run: |
        gcloud auth configure-docker
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t ${{ env.DOCKER_IMAGE }} ./endpoint
        docker push ${{ env.DOCKER_IMAGE }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform/

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: terraform/

    - name: Get GKE Credentials
      run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

    - name: Deploy to GKE
      run: kubectl apply -f k8s/deployment.yaml  # Adjust to your Kubernetes deployment manifest location

    - name: Wait for Deployment to Complete
      run: kubectl rollout status deployment/interview-api-deployment

    - name: Verify API is Accessible
      run: |
        sleep 30
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://35.188.216.83/api/v1/time)
        if [ $RESPONSE -ne 200 ]; then
          echo "API is not accessible, received HTTP status $RESPONSE"
          exit 1
        fi
      shell: bash
